# Basic configuration file
app:
  name: "My Application"
  version: "1.0.0"
  port: 3000

database:
  host: "localhost"
  port: 5432
  name: "myapp_db"

environment: "development"

features:
  - "authentication"
  - "logging"
  - "api"
