name: Deploy Calculator App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linters
        run: |
          npm install -g htmlhint stylelint eslint

      - name: Lint HTML
        run: htmlhint "**/*.html" || echo "⚠️ HTML issues found"

      - name: Lint CSS
        run: stylelint "**/*.css" || echo "⚠️ CSS issues found"

      - name: Lint JS
        run: eslint "**/*.js" || echo "⚠️ JavaScript issues found"

      - name: Deploy to GitHub Pages
        # ✅ Deploy even if lint fails
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
